base_dir: 's3://team-model-data-preprocess/test/datasets/test_korean_jsonl_data/'
targets: 
    - 0
    - 1
output_dir: 's3://team-model-data-preprocess/test/output/test_dedup'

n_dist: 10
n_output: 1
num_expand: 10
sim_threshold: 0.8
n_gram: 13
char_level: false
seed: 1