base_dir: 's3://team-model-data-preprocess/test/datasets/test_korean_jsonl_data/'
targets:
  - 0
  - 1
output_dir: 's3://team-model-data-preprocess/test/output/test_korean'

n_dist: 10
n_output: 1
min_doc_len: 50
max_doc_len: 100000
min_mean_word_len: 3
max_mean_word_len: 10
symbol_to_word_ratio: 0.1
bullet_point_ratio: 0.9
ellipsis_ratio:  0.3
korean_word_ratio: 0.25